### ISSUE TITLE
PR ready, mjs files resolving before js files as in CRA#4085 #10

### ISSUE THREAD

**Issue by a-tokyo** [ro-savage/react-scripts-cssmodules#11]
Is there any news on merging this?

It is an actual bug that was fixed in CRA, I opened the PR a while ago and would appreciate any response. :) 

https://github.com/ro-savage/react-scripts-cssmodules/pull/10

@ro-savage 

Thanks!

**Comment by ro-savage** [comment]
Thanks for this report and the PR.

It's been fixed by upgrading to 1.1.5

Sorry for the very long delay on this.
