### ISSUE TITLE
Request:  put localIdentName on the command line

### ISSUE THREAD

**Issue by gregsandell** [ro-savage/react-scripts-cssmodules#12]
The `localIdentName` that zero-configuration _react-scripts-cssmodules_ provides is much too bulky for me, and I would like to simplify it considerably.  (Not that it matters, but for myself I am thinking of using `[hash:base64:5]_[local]`) . I don't want to eject, so can the script be modified to give us control over `localIdentName`?  Thanks

**Comment by ro-savage** [comment]
This repo exactly replicates CRA v2.0's implementation of CSS Modules. If you wish to change it, you'll need to make an issue in CRA and have it approved.
