### ISSUE TITLE
CRA v2 now has support for SCSS modules

### ISSUE THREAD

**Issue by benknight** [ro-savage/react-scripts-cssmodules#15]
https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/config/webpack.config.dev.js#L37

Added here: https://github.com/facebook/create-react-app/pull/4195

This issue is to resync this repo with the latest v2 config so that this project can be used with components that use SCSS modules until CRA v2 is released.

This was mentioned in the comments on #13 after it was closed, but there was no follow up by the author.  Opening a new issue for reconsideration.

**Comment by ro-savage** [comment]
Apologises, I didn't get notifications for those comments.

@benknight @danoc - Happy to take a PR to bring this package up to date with SCSS changes from CRAv2.

**Comment by danoc** [comment]
Thanks, @ro-savage — I won't have time to work on this, but maybe @benknight is interested. FWIW, CRA v2 is expected to be released within the next two weeks: https://github.com/facebook/create-react-app/issues/5024

**Comment by ro-savage** [comment]
Once CRA v2 is released, this package will stop being updated/maintained.

Still happy for someone to do a PR, but for most people, just upgrading to CRA v2 is the much better option as it includes many enhancements.

**Comment by benknight** [comment]
Agreed, I created this issue just before learning that CRA v2 was about to be released.  Willing to wait for that.
