### ISSUE TITLE
asset-manifest.json only contains one main.css file

### ISSUE THREAD

**Issue by jpstevens** [ro-savage/react-scripts-cssmodules#7]
When using something like the following:
```js
import './App.css'; // regular CSS import
import s from './test.module.css'; // CSS module
```

The asset manifest comes out like so:
```json
{
  "main.css": "static/css/main-cssmodules.29f7c281.css",
  "main.css.map": "static/css/main-cssmodules.29f7c281.css.map",
  "main.js": "static/js/main.009f56a3.js",
  "main.js.map": "static/js/main.009f56a3.js.map",
  "static/media/logo.svg": "static/media/logo.5d5d9eef.svg"
}
```

It's missing the entry for `main.c17080f1.css` and `main.c17080f1.min.css`.

Any ideas why?

**Comment by ro-savage** [comment]
Unfortunately I don't have the answer.

The [ManifestPlugin](https://github.com/danethurber/webpack-manifest-plugin/tree/1.x) should be auto generating it based on all the files created during the webpack build (I believe it looks at `compilation.getStats()` from webpacks build process).

It should therefore pick it up. I might be an issue upstream, as we shouldn't need to change anything.

Happy for someone to take a look and investigate.

**Comment by berdyshev** [comment]
I'm experiencing the same issue

**Comment by ro-savage** [comment]
Closing this, as it is currently not being actioned.

If anyone knows why this happens, feel free to submit a PR.
