### ISSUE TITLE
Modify class naming scheme

### ISSUE THREAD

**Issue by digster** [ro-savage/react-scripts-cssmodules#9]
Is there a way to alter the final class naming scheme? We use SSR and babel to name the final css classes to [local]-[hash:base64:5]. We need the naming scheming to be the same at both the server and client side.

**Comment by ro-savage** [comment]
No, we don't allow this. As it's the same naming scheme as CRA will have. 

I'd suggest using one of the forks that allows you to customise webpack completely.

There will actually be an update coming out for this to update the naming scheme, as a new naming convention was just merged into CRA v2. This will be a breaking change for `react-scripts-cssmodules`.
